# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 981dd46e5d857a0a7f66570d14321b5d38db79f6b935605b0649ab6907742186de25a9ec6e52675a4e34dbcfbb1138502a3e43afc6147a75de87ef9f58276b0c

test:
  secret_key_base: 9c090d880671d9faf01df976791a44cd2c7f25abaa7bd51d758a7d90f25eaf767db51887da7af7b2f333a426eca0d3cdf9fff25ad0ed9b96c61026dae1abe5c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
